version: '3.9'
services:
  backend:
    network_mode: bridge
    build:
      dockerfile: Dockerfile
      context: './backend'
    environment:
      - JIRA_API_KEY=x3#g7!ndswqo5bbz
      - CURRENT_YEAR=2021
      - JIRA_USER_ID=ebs_hrs_api@wisc.edu
      - HOST_URL=https://jira.doit.wisc.edu/jira
    ports:
      - 5000:5000
  frontend:
    network_mode: bridge
    build:
      dockerfile: Dockerfile
      context: './frontend'
    depends_on:
      - backend
    ports:
      - 3000:3000
    
